# 2層ニューラルネットワーククラスの実装
* 2_7_simple_NeuralNetwork_trainee.ipynbでは、非常にシンプルなニューラルネットワークを実装した。
* ここでは、2層ニューラルネットワークのクラスを実装する。
* 2層ニューラルネットワークなので、推定するパラメータとして、W1, W2, b1, b2を定義する

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

try:
    from google.colab import files
    print('Google Colab. 上での実行です')
    print('「ファイルを選択」から、notebook/commonフォルダのactivations.py、grad.py、loss.pyを選択し、アップロードしてください')
    print('===========')
    files.upload()
    !mkdir common
    !mv activations.py ./common
    !mv grad.py ./common
    !mv loss.py ./common
except:
    print('ローカル環境での実行です')

from common.activations import softmax, sigmoid
from common.grad import numerical_gradient
from common.loss import cross_entropy_error

Google Colab. 上での実行です
「ファイルを選択」から、DAY1/2_notebook/commonフォルダのactivations.py、grad.py、loss.pyを選択し、アップロードしてください


Saving activations.py to activations.py
Saving grad.py to grad.py
Saving loss.py to loss.py


## 2層ニューラルネットワーククラスの実装

### [演習]
* 2層ニューラルネットワークにおいて、予測、損失、勾配を計算する以下のクラスを完成させましょう

In [ ]:
import numpy as np

class TwoLayerNet():
    def __init__(self, input_size, hidden_size, output_size):
        
        # 重みの初期化
        self.params = {}
        init_std=0.01
        np.random.seed(1234)
        self.params["W1"] = init_std * np.random.randn(input_size, hidden_size)
        self.params["b1"] = np.zeros(hidden_size)
        self.params["W2"] = init_std * np.random.randn(hidden_size, output_size)
        self.params["b2"] = np.zeros(output_size)
                
    def predict(self, x):
        """
        予測関数
        x : 入力データ
        """
        W1, W2 = self.params["W1"], self.params["W2"]
        b1, b2 = self.params["b1"], self.params["b2"]
        
        h1 = np.dot(x, W1) + b1
        z1 = sigmoid(h1)
        h2 = np.dot(z1, W2) + b2
        y = softmax(h2)
        return y
    
    def loss(self, x, t):
        """
        損失関数
        x : 入力データ
        t : 正解データ
        """
        y = self.predict(x)
        loss = cross_entropy_error(y, t)
        return loss
    
    def gradient(self, x, t):
        """
        勾配計算関数
        """
        grads={}
        f = self.loss
        grads["W1"] = numerical_gradient(f, x, self.params["W1"], t)
        grads["b1"] = numerical_gradient(f, x, self.params["b1"], t)
        grads["W2"] = numerical_gradient(f, x, self.params["W2"], t)
        grads["b2"] = numerical_gradient(f, x, self.params["b2"], t)
        return grads

In [ ]:
# 重み初期値の確認
tnet = TwoLayerNet(input_size=5, hidden_size=4, output_size=3)
print(tnet.params["W1"])
print(tnet.params["b1"])
print(tnet.params["W2"])
print(tnet.params["b2"])
print()
print("行列の形状の確認")
print(tnet.params["W1"].shape)
print(tnet.params["b1"].shape)
print(tnet.params["W2"].shape)
print(tnet.params["b2"].shape)

[[ 4.71435164e-03 -1.19097569e-02  1.43270697e-02 -3.12651896e-03]
 [-7.20588733e-03  8.87162940e-03  8.59588414e-03 -6.36523504e-03]
 [ 1.56963721e-04 -2.24268495e-02  1.15003572e-02  9.91946022e-03]
 [ 9.53324128e-03 -2.02125482e-02 -3.34077366e-03  2.11836468e-05]
 [ 4.05453412e-03  2.89091941e-03  1.32115819e-02 -1.54690555e-02]]
[0. 0. 0. 0.]
[[-0.00202646 -0.00655969  0.00193421]
 [ 0.00553439  0.01318152 -0.00469305]
 [ 0.00675554 -0.01817027 -0.00183109]
 [ 0.01058969 -0.0039784   0.00337438]]
[0. 0. 0.]

行列の形状の確認
(5, 4)
(4,)
(4, 3)
(3,)


### N=1のxを入力した時の勾配計算

In [ ]:
x = np.array([1,2,3,4,5])
t = np.array([0, 0, 1])

# 勾配を計算する
grads = tnet.gradient(x, t)
print("勾配")
for key, value in grads.items():
    print(key,"=")
    print(value)
    print()

print()
print("勾配行列の形状")
for key, value in grads.items():
    print(key,"=", value.shape)

勾配
W1 =
[[-1.03413179e-03  2.32730561e-03 -6.24394595e-04  7.61957164e-08]
 [-2.06826358e-03  4.65461121e-03 -1.24878919e-03  1.52390323e-07]
 [-3.10239536e-03  6.98191679e-03 -1.87318377e-03  2.28588259e-07]
 [-4.13652712e-03  9.30922234e-03 -2.49757835e-03  3.04782866e-07]
 [-5.17065886e-03  1.16365278e-02 -3.12197291e-03  3.80979692e-07]]

b1 =
[-1.03413179e-03  2.32730561e-03 -6.24394595e-04  7.61957164e-08]

W2 =
[[ 0.17246339  0.16921786 -0.34168125]
 [ 0.15758025  0.15461479 -0.31219504]
 [ 0.17830481  0.17494934 -0.35325415]
 [ 0.1629945   0.15992716 -0.32292166]]

b2 =
[ 0.33665038  0.33031505 -0.66696543]


勾配行列の形状
W1 = (5, 4)
b1 = (4,)
W2 = (4, 3)
b2 = (3,)


### N=1のxを入力した時の予測

In [ ]:
x = np.array([1,2,3,4,5])
t = np.array([0, 0, 1])
p = tnet.predict(x)
print("p=", p)
print("pの合計=", p.sum())
print()

p= [0.33665048 0.33031515 0.33303437]
pの合計= 1.0



### N=2のxを入力した時の予測

In [ ]:
x = np.array([[1,2,3,4,5],
                        [1,2,3,4,5]])
t = np.array([[0, 0, 1],
                       [0, 0, 1]])
p = tnet.predict(x)
print("p=", p)
print("pの合計=", p.sum(axis=1))

p= [[0.33665048 0.33031515 0.33303437]
 [0.33665048 0.33031515 0.33303437]]
pの合計= [1. 1.]


### N=3のxを入力した時の予測

In [ ]:
x = np.array([[1,2,3,4,5],
                        [1,2,3,4,5],
                        [1,2,3,4,5]])
t = np.array([[0, 0, 1],
                        [0, 0, 1],
                        [0, 0, 1]])
p = tnet.predict(x)
print("p=", p)
print("pの合計=", p.sum(axis=1))

p= [[0.33665048 0.33031515 0.33303437]
 [0.33665048 0.33031515 0.33303437]
 [0.33665048 0.33031515 0.33303437]]
pの合計= [1. 1. 1.]
