# 初期値の影響(固定値)

In [ ]:
import numpy as np

## 初期値が0の場合

In [ ]:
num_in = 5
X = np.arange(num_in)
num_node1 = 7
W1 = np.zeros((num_in, num_node1))
num_node2 = 5
W2 = np.zeros((num_node1, num_node2))
num_node3 = 3
W3 = np.zeros((num_node2, num_node3))
print("X=", X)
print("W1=", W1)
print("W2=", W2)
print("W3=", W3)

X= [0 1 2 3 4]
W1= [[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
W2= [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
W3= [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### 順伝播を行う

In [ ]:
h1 = np.dot(X, W1)
h2 = np.dot(h1, W2)
h3 = np.dot(h2, W3)
print("h1=", h1)
print("h2=", h2)
print("h3=", h3)

h1= [0. 0. 0. 0. 0. 0. 0.]
h2= [0. 0. 0. 0. 0.]
h3= [0. 0. 0.]


* 中間層のノードの値は全て0になる
* この状態で誤差逆伝播をやっても学習は進まない

## 初期値が1の場合

In [ ]:
num_in = 5
X = np.arange(num_in)
num_node1 = 7
W1 = np.ones((num_in, num_node1))
num_node2 = 5
W2 = np.ones((num_node1, num_node2))
num_node3 = 3
W3 = np.ones((num_node2, num_node3))
print("X=", X)
print("W1=", W1)
print("W2=", W2)
print("W3=", W3)

X= [0 1 2 3 4]
W1= [[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
W2= [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
W3= [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### 順伝播を行う

In [ ]:
h1 = np.dot(X, W1)
h2 = np.dot(h1, W2)
h3 = np.dot(h2, W3)
print("h1=", h1)
print("h2=", h2)
print("h3=", h3)

h1= [10. 10. 10. 10. 10. 10. 10.]
h2= [70. 70. 70. 70. 70.]
h3= [350. 350. 350.]


* 各中間層のノードの値は同じになる。

## 初期値が1と2の場合

In [ ]:
num_in = 5
X = np.arange(num_in)
num_node1 = 7
W1 = np.ones((num_in, num_node1))

# 1箇所だけ重みの初期値を2にする
W1[2,2] = 2.0

num_node2 = 5
W2 = np.ones((num_node1, num_node2))
num_node3 = 3
W3 = np.ones((num_node2, num_node3))
print("X=", X)
print("W1=", W1)
print("W2=", W2)
print("W3=", W3)

X= [0 1 2 3 4]
W1= [[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 2. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
W2= [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
W3= [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
h1 = np.dot(X, W1)
h2 = np.dot(h1, W2)
h3 = np.dot(h2, W3)
print("h1=", h1)
print("h2=", h2)
print("h3=", h3)

h1= [10. 10. 12. 10. 10. 10. 10.]
h2= [72. 72. 72. 72. 72.]
h3= [360. 360. 360.]


* 2つ目の中間層以降は同じ値になる。

### [演習]
* W1,W2,W3の初期値を3に変更してみましょう
* W1,W2,W3の初期値を-3に変更してみましょう

### [ポイント]
* ノードを沢山設定することの意義は、それぞれのノードに別々の役割を担わせることができること。これにより、複雑な関係性を表現することができる。
* もし、ノードの出力値が同じになるのであれば、それは、ノードを1つだけ配置していることと同じ意味になる。
* つまり、初期値がバラけることによって、ノードを沢山設定する意味が出てくる。
* では、初期値をバラけさせるにはどうすればいいか？