# Embeddingレイヤを確認する
Embeddingレイヤは、単語IDを埋め込みベクトルに変換するためのレイヤである

In [1]:
import numpy as np

In [2]:
# 確認
a = b = np.ones((5,3))
print("a=",a, "\n")
print("b=",b, "\n")
a.fill(3)  #　numpyの配列の各要素に同じ値を代入する
b = 3 # 変数に値を代入する
print("a=",a, "\n")
print("b=",b, "\n")
print()

dW = np.random.rand(2,3)
print(dW)
print()
idx = 1
dout = np.array([1,2,3])
np.add.at(dW, idx, dout) #  dWのidx行目にベクトルdoutを加える処理
print(dW)

a= [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

b= [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

a= [[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]] 

b= 3 


[[0.75742013 0.36703447 0.79939089]
 [0.39677436 0.61034915 0.32105759]]

[[0.75742013 0.36703447 0.79939089]
 [1.39677436 2.61034915 3.32105759]]


In [3]:
class Embedding:
    def __init__(self, W):
        """
        W : 重み行列, word2vecの埋め込み行列に相当する。配列形状は、(語彙数、埋め込みベクトルの要素数)
        """
        self.params = [W] # 要素は1つだけであるが、他のレイヤと仕様を揃えるため、あえてリストで定義
        self.grads = [np.zeros_like(W)] # 要素は1つだけであるが、他のレイヤと仕様を揃えるため、あえてリストで定義
        self.idx = None

    def forward(self, idx):
        """
        順伝播計算
        """
        W = self.params[0]
        self.idx = idx
        
        # 埋め込み行列から埋め込みベクトルを取り出す
        out = W[idx]
        
        return out

    def backward(self, dout):
        """
        逆伝播計算
        """
        # gradsというリストの1要素目を参照する
        dW = self.grads[0]
        
        # 配列の全ての要素に0を代入する
        dW.fill(0)
        
        # dWのidxの場所にdoutを加える
        np.add.at(dW, self.idx, dout)
        return None

In [4]:
V = 10 # 語彙数
D = 3 # 埋め込みベクトルの要素数

# パラメータの初期化
embed_W = np.random.randn(V, D) 
print("embed_W=", embed_W)
print()

# オブジェクトの生成
emb = Embedding(embed_W)

# 単語ID
idx = 2

# 順伝播計算
emb.forward(idx)

# 逆伝播計算
dout = np.arange(D)
print("dout=", dout)
print()
emb.backward(dout)
print("dW=", emb.grads[0])
print()

embed_W= [[ 0.38920804 -0.07930378 -0.69509834]
 [-0.35006118  1.02021864 -0.91219735]
 [-0.0519599  -2.21822357 -2.11739736]
 [ 0.73431946  0.98623112 -2.42078412]
 [ 1.7784221   0.96226115  0.45536535]
 [ 0.92357557  0.12315335  0.75173579]
 [-0.32875561  0.32420245  0.08943111]
 [-0.18860348 -0.75743658  0.44541143]
 [-0.68366388  1.04258691 -1.25271607]
 [ 0.76258151 -1.00652386  1.09406112]]

dout= [0 1 2]

dW= [[0. 0. 0.]
 [0. 0. 0.]
 [0. 1. 2.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

